CREATE USER 'sgpuser'@'%' IDENTIFIED BY 'pruebas123';

GRANT ALL ON *.* TO 'sgpuser'@'localhost';
GRANT ALL ON *.* TO 'sgpuser'@'%';
FLUSH PRIVILEGES;

GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'sgpuser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

DROP DATABASE sgp;
CREATE SCHEMA sgp DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
